repos:
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.8.0
    hooks:
      - id: mypy
        name: mypy
        description: "Mypy static type checker"
  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort
  - repo: https://github.com/psf/black
    rev: 23.12.1
    hooks:
      - id: black
        name: black
        entry: black
        description: "Black: The uncompromising code formatter."
        language: python
        language_version: python3.10
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: "v0.1.14"
    hooks:
      - id: ruff